// Generated by CoffeeScript 1.8.0
(function() {
  var chalk, cleanInput, closeSocket, net, newSocket, receiveData, server, sockets;

  net = require('net');

  chalk = require('chalk');

  sockets = [];

  receiveData = function(socket, data) {
    var cleanData, _i, _len, _results;
    cleanData = cleanInput(data);
    if (cleanData === '@quit') {
      return socket.end(chalk.cyan('Goodbye!\n'));
    } else {
      _results = [];
      for (_i = 0, _len = sockets.length; _i < _len; _i++) {
        socket = sockets[_i];
        _results.push(socket.write(data));
      }
      return _results;
    }
  };

  cleanInput = function(data) {
    return data.toString().replace(/(\r\n|\n|\r)/gm, '');
  };

  closeSocket = function(socket) {
    var i;
    i = sockets.indexOf(socket);
    if (i !== -1) {
      return socket.splice(i, 1);
    }
  };

  newSocket = function(socket) {
    sockets.push(socket);
    socket.write(chalk.green('Hello World!'));
    socket.on('data', function(data) {
      return receiveData(socket, data);
    });
    socket.on('end', function() {
      return closeSocket(socket);
    });
    return console.log(chalk.yellow('get connected!'));
  };

  server = net.createServer(newSocket);

  server.listen(3000);

}).call(this);
